[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.104.3'

[context]
[context.branch-deploy]
command = 'hugo -F -b $http://samriti-io'

[context.deploy-preview]
command = 'hugo -F -b $http://samriti-io'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
